# Tamanho dos objetos

In [1]:
# Funções:
# length, nrow, ncol, dim

### Função length

In [2]:
x <- c(1, 2, 3, 4, 5, 6, 7)
n <- length(x)
cat(paste('O tamanho de x é:', n))

O tamanho de x é: 7

### Matrix

In [3]:
x <- matrix(1:20, nrow = 4, ncol = 5)
print(x)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    5    9   13   17
[2,]    2    6   10   14   18
[3,]    3    7   11   15   19
[4,]    4    8   12   16   20


In [7]:
# Número de linhas, colunas e elementos
my.nrow <- nrow(x)
my.ncol <- ncol(x)
my.length <- length(x)

cat(paste("O número de linhas é", my.nrow))
cat(paste("\nO número de colunas é", my.ncol))
cat(paste("\nO número de colunas é", my.length))

O número de linhas é 4
O número de colunas é 5
O número de colunas é 20

In [8]:
# Dimensão do objeto
print(dim(x))

[1] 4 5


### Array

In [9]:
my.array <- array(1:9, dim = c(3, 3, 3))
print(my.array)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 3

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9



In [10]:
print(dim(my.array))

[1] 3 3 3
