## Matrizes

In [1]:
harvard <- c(1, 1, 1, 1, 3)
stanford <- c(2, 9, 3, 4, 10)
mit <- c(3, 3, 2, 2, 1)
cambridge <- c(4, 2, 6, 13, 48)
oxford <- c(5, 7, 12, 9, 15)
columbia <- c(6, 13, 13, 12, 5)

In [2]:
# Combinando vários vetores por linha - rbind
harv_stan <- rbind( harvard, stanford )

harv_stan

[,1] [,2] [,3] [,4] [,5]
harvard  1    1    1    1     3  
stanford 2    9    3    4    10

In [3]:
rbind(harv_stan, mit)

[,1] [,2] [,3] [,4] [,5]
harvard  1    1    1    1     3  
stanford 2    9    3    4    10  
mit      3    3    2    2     1

In [4]:
uni_matrix <- rbind(harv_stan, mit, cambridge, oxford, columbia)

uni_matrix

[,1] [,2] [,3] [,4] [,5]
harvard   1     1    1    1    3  
stanford  2     9    3    4   10  
mit       3     3    2    2    1  
cambridge 4     2    6   13   48  
oxford    5     7   12    9   15  
columbia  6    13   13   12    5

In [5]:
# Adicionar nomes
# Linhas = rownames()
# Colunas = colnames()

In [8]:
colunas <- c('world.rank', 'quality.of.education', 'influence', 'broad.impact', 'patents')
colnames(harv_stan) <- colunas

harv_stan

world.rank quality.of.education influence broad.impact patents
harvard  1          1                    1         1             3     
stanford 2          9                    3         4            10

In [9]:
rownames(harv_stan)

[1] "harvard"  "stanford"

In [11]:
colnames(uni_matrix) <- colunas
uni_matrix

world.rank quality.of.education influence broad.impact patents
harvard   1           1                    1         1            3     
stanford  2           9                    3         4           10     
mit       3           3                    2         2            1     
cambridge 4           2                    6        13           48     
oxford    5           7                   12         9           15     
columbia  6          13                   13        12            5

In [12]:
valor_anual <- c(43280, 45000, 45016, 49350, 28450, 55161)

In [13]:
# Tamanho da matriz
dim(uni_matrix)

[1] 6 5

In [14]:
# Número de linhas
dim(uni_matrix)[1]

[1] 6

In [15]:
# Verificando se possuem o mesmo tamanho
dim(uni_matrix)[1] == length(valor_anual)

[1] TRUE

In [16]:
# Combinando vetores por coluna - cbind
uni_matrix <- cbind(uni_matrix, valor_anual)

uni_matrix

world.rank quality.of.education influence broad.impact patents
harvard   1           1                    1         1            3     
stanford  2           9                    3         4           10     
mit       3           3                    2         2            1     
cambridge 4           2                    6        13           48     
oxford    5           7                   12         9           15     
columbia  6          13                   13        12            5     
          valor_anual
harvard   43280      
stanford  45000      
mit       45016      
cambridge 49350      
oxford    28450      
columbia  55161

In [18]:
# Extraindo valor da matriz
patents_stanford <- uni_matrix[2, 5]

patents_stanford

[1] 10

In [19]:
patents_stanford <- uni_matrix['stanford', 'patents']

patents_stanford

[1] 10

In [20]:
stanford <- uni_matrix['stanford', 3:5]

stanford

influence broad.impact      patents 
           3            4           10

In [22]:
uni_matrix[c('oxford', 'harvard'), c('quality.of.education', 'valor_anual')]

quality.of.education valor_anual
oxford  7                    28450      
harvard 1                    43280

In [23]:
oxford_influence <- uni_matrix['oxford', 'influence']
oxford_influence

[1] 12

In [24]:
cam_stan_patents <- uni_matrix[c('cambridge', 'stanford'), 'patents']

cam_stan_patents

cambridge  stanford 
       48        10

In [25]:
uni_matrix['harvard',]

world.rank quality.of.education            influence 
                   1                    1                    1 
        broad.impact              patents          valor_anual 
                   1                    3                43280

In [26]:
uni_matrix[, 'valor_anual']

harvard  stanford       mit cambridge    oxford  columbia 
    43280     45000     45016     49350     28450     55161

In [27]:
uni_matrix[, c('influence', 'broad.impact')]

influence broad.impact
harvard    1         1          
stanford   3         4          
mit        2         2          
cambridge  6        13          
oxford    12         9          
columbia  13        12

In [28]:
oxford_rank <- uni_matrix['oxford',]
oxford_rank

world.rank quality.of.education            influence 
                   5                    7                   12 
        broad.impact              patents          valor_anual 
                   9                   15                28450

In [29]:
influence <- uni_matrix[, 'influence']
influence

harvard  stanford       mit cambridge    oxford  columbia 
        1         3         2         6        12        13

In [31]:
harv_mit_rank <- uni_matrix[c('harvard', 'mit'),]
harv_mit_rank

world.rank quality.of.education influence broad.impact patents
harvard 1          1                    1         1            3      
mit     3          3                    2         2            1      
        valor_anual
harvard 43280      
mit     45016

In [32]:
influence_patents <- uni_matrix[, c('influence', 'patents')]
influence_patents

influence patents
harvard    1         3     
stanford   3        10     
mit        2         1     
cambridge  6        48     
oxford    12        15     
columbia  13         5

In [33]:
rank( uni_matrix[, 'quality.of.education'] )

harvard  stanford       mit cambridge    oxford  columbia 
        1         5         3         2         4         6